name: React.js CI

on:
  push:
    branches: [main]
  pull_request: #optional
    branches: [main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ${{ matrix.os }} #ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [16.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use React.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci # similar to npm install
      - run: npm test
      - run: npm run build --if-present
